version: "3.4"
services:
  singular_cli:
    build: "."
    environment:
      - SINGULAR_PATH=/data
      - SINGULAR_DOWNLOAD=/download
    volumes:
      - .:/data
      - ./data:/download
    entrypoint: 
      - python3
      - /data/singular.py

  singular_frontend:
    build: "frontend"
    restart: always
    environment:
      - SINGULAR_SETTINGS_FOLDER=/data/
      - SINGULAR_SETTINGS_FILE=settings.json
      - SINGULAR_DOCKER_NAME=singular_singular_cli
    volumes:
      - .:/data
    ports:
      - "7500:7500"
      - "7501:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - /usr/bin/docker:/usr/bin/docker 
      - ./:/data
    entrypoint:
      - python3
      - /data/frontend/serve.py
   
  nginx:
    image: "nginx"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
